### PR TITLE
Abstract handling of messages to separate class

### PR DESCRIPTION
**Pull request by hickey**
As I was working on #19 in preparation for a release, I was encountering a number of issues in trying to synchronize data and get the data into a steady state. 

In building a message class to maintain an internal message DB added the observer pattern to allow the class to notify the front-end code changes in communicate state changes in the DB. This allows the front-end code to be more event driven and a little bit more performant. 

With this rewrite, the main code of the front-end (`chat.js`) has become more structured and simpler to understand the flow. A number of unused and useless variables and some variables have been moved into functions to provide better scoping. 

From what I can tell all the same functionality of the old code is still in place. One possible enhancement has been better coordination between the channel selector and the send message channel selector. 

The only outstanding issue is that the audio alert is played anytime the channel is changed. This will take a bit more thought on how overcome and will be a patch release in the future. 

#19 is blocked on this PR.

### CODE REVIEW

**Comment by hickey** [comment]
@gerner I did see the W7AW and W7ACS MeshChat servers last night, you should should still be connected through some of the supernodes. So you should be able to get to the test instance I have running if you want to try anything out.

**Comment by hickey** [comment]
I am going to just have to move forward with this PR. I am pretty confident it is good since it has been running on a node for a while and three was a lot of debugging done to replace existing code. If any code improvements are found later on, the code can be refactored at that point.

**Comment by gerner** [comment]
@hickey I'd like to hear your thoughts about message syncing. I spent a little time thinking about inter-node syncing in the past. You're clearly pretty deep in this, so I'm happy to be a rubber duck for you and hear your plans for improving sync.

I see messaging syncing as one of the most important features and also one that can be fragile. So I'm looking forward to improvements there and willing to help however I can.

**Comment by gerner** [comment]
Maybe you can join NWMesh, or we could hop on another zoom call some time?

**Comment by hickey** [comment]
Right now my primary focus is moving to getting MeshChat to work in non-node environments (i.e. Linux). This will be the primary focus for the next release so that all the old installations can start to go away and run on currently supported versions. I don't even really consider `v2.0` - `v2.10` currently supported, but I will try to do what I can to help out getting an installation running. After MeshChat is running on Linux, I will be able to start working on building the testing framework so that regression testing can be done to try to make sure we don't have any errors popping back up. 

That is when I will start putting some effort back into the sync process. I have an issue (#17) where I will be keeping track of notes and thoughts on the matter. I welcome anyone to contribute to the issue if they have any good thoughts on how syncing can be improved. 

Several months ago (November?) I was on a call with the Seattle guys (you were absent, but several people were wishing you were on the call) and I remember going into groups.io to sign up for the mailing list you have so that I could get on the calls sometimes. I thought that I had received a response saying that I was subscribed, but I don't see anything applicable in my list of subscriptions in groups.io. Maybe someone dropped me or I am thinking of something else? I have just mashed the button to subscribe to the list again. Maybe this time it will stick.

**Pull request merged**
